### ISSUE TITLE
On removal of an image, cache and register only clear when in &#x60;--watch&#x60; mode

### ISSUE THREAD

**Issue by andrewrubin** [wethegit/masher#12]
This is not a huge deal, but we should fix.

You can remove images, and subsequently run `@wethegit/masher`, but the cache + register will not clear

**Comment by liamegan** [comment]
Can you elaborate on this a little for me? What're the steps, what's the expected and actual state?

**Comment by andrewrubin** [comment]
Sure thing. And let me know if you think this is a non-issue.

If you delete a file from your input directory, and _then_ run a one-off mash (via `npx @wethegit/masher`), the cache, register, and output files are not cleared of that image. The cleanup only seems to work in `--watch` mode.

**Comment by marlonmarcello** [comment]
Fixed #13
